learning_rate: 0.1
gamma: 0.99

epsilon_start: 1.0
epsilon_end: 0.01
epsilon_decay: 0.9995

num_episodes: 15000
max_steps: 1000

num_bins: [100, 100]

use_reward_shaping: false
shaping_scale: 1000.0

use_cost_penalty: true
cost_coefficient: 0.1